#!/bin/sh
# .env → AppSecrets.swift + Generated.xcconfig + GeneratedInfo.plist
#
# Xcode Run Script fazında Compile Sources'tan önce çalışır. .env yoksa
# boş değerler üretir; uygulama UnconfiguredProductService ile açılır.
# Google URL scheme xcconfig'ten bir derleme geride kalır; bu yüzden
# GeneratedInfo.plist'e literal basılır (INFOPLIST_FILE). Paketlenmiş
# Info.plist'i sonradan yamamak Xcode 26'da "mutable output" hatası verir.
set -eu

ROOT="${SRCROOT:-$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)}"
ENV_FILE="$ROOT/.env"
SECRETS_DIR="$ROOT/Bond/Core/Generated"
SECRETS_SWIFT="$SECRETS_DIR/AppSecrets.swift"
XCCONFIG_OUT="$ROOT/Config/Generated.xcconfig"

read_env() {
    key="$1"
    default="${2-}"
    if [ ! -f "$ENV_FILE" ]; then
        printf '%s' "$default"
        return
    fi
    line=$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)
    if [ -z "$line" ]; then
        printf '%s' "$default"
        return
    fi
    value=${line#*=}
    value=$(printf '%s' "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
    printf '%s' "$value"
}

escape_swift() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

SUPABASE_HOST=$(read_env SUPABASE_HOST)
SUPABASE_PUBLISHABLE_KEY=$(read_env SUPABASE_PUBLISHABLE_KEY)
GOOGLE_CLIENT_ID=$(read_env GOOGLE_CLIENT_ID)
GOOGLE_SERVER_CLIENT_ID=$(read_env GOOGLE_SERVER_CLIENT_ID)
GOOGLE_REVERSED_CLIENT_ID=$(read_env GOOGLE_REVERSED_CLIENT_ID)

# iOS client ID `….apps.googleusercontent.com` → URL scheme `com.googleusercontent.apps.…`
if [ -z "$GOOGLE_REVERSED_CLIENT_ID" ] && [ -n "$GOOGLE_CLIENT_ID" ]; then
    case "$GOOGLE_CLIENT_ID" in
        *.apps.googleusercontent.com)
            GOOGLE_REVERSED_CLIENT_ID="com.googleusercontent.apps.${GOOGLE_CLIENT_ID%.apps.googleusercontent.com}"
            ;;
    esac
fi

mkdir -p "$SECRETS_DIR" "$ROOT/Config"

# Info.plist $(GOOGLE_REVERSED_CLIENT_ID) xcconfig'ten bir derleme geride kalır.
# Aynı derlemede literal basılmış bir kopya üret; Xcode bunu INFOPLIST_FILE olarak kullanır.
python3 - "$ROOT/Config/Info.plist" "$ROOT/Config/GeneratedInfo.plist" "$GOOGLE_REVERSED_CLIENT_ID" <<'PY'
import sys
from pathlib import Path

src, dst = sys.argv[1], sys.argv[2]
scheme = sys.argv[3] if len(sys.argv) > 3 else ""
Path(dst).write_text(Path(src).read_text().replace("$(GOOGLE_REVERSED_CLIENT_ID)", scheme))
PY

HOST_SWIFT=$(escape_swift "$SUPABASE_HOST")
KEY_SWIFT=$(escape_swift "$SUPABASE_PUBLISHABLE_KEY")
GOOGLE_ID_SWIFT=$(escape_swift "$GOOGLE_CLIENT_ID")
GOOGLE_SERVER_SWIFT=$(escape_swift "$GOOGLE_SERVER_CLIENT_ID")
GOOGLE_REVERSED_SWIFT=$(escape_swift "$GOOGLE_REVERSED_CLIENT_ID")

cat > "$SECRETS_SWIFT" <<EOF
// Generated by Scripts/sync-env.sh — do not edit.
import Foundation

enum AppSecrets {
    static let supabaseHost = "${HOST_SWIFT}"
    static let supabasePublishableKey = "${KEY_SWIFT}"
    static let googleClientID = "${GOOGLE_ID_SWIFT}"
    static let googleServerClientID = "${GOOGLE_SERVER_SWIFT}"
    static let googleReversedClientID = "${GOOGLE_REVERSED_SWIFT}"

    static var supabaseURL: URL? {
        let host = supabaseHost.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !host.isEmpty else { return nil }
        return URL(string: "https://\\(host)")
    }
}
EOF

# xcconfig treats "//" as a comment. Split the slash so SUPABASE_URL stays intact.
cat > "$XCCONFIG_OUT" <<EOF
// Generated by Scripts/sync-env.sh — do not edit.
SUPABASE_SLASH = /
SUPABASE_HOST = ${SUPABASE_HOST}
SUPABASE_URL = https:\$(SUPABASE_SLASH)\$(SUPABASE_SLASH)\$(SUPABASE_HOST)
SUPABASE_PUBLISHABLE_KEY = ${SUPABASE_PUBLISHABLE_KEY}
GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
GOOGLE_SERVER_CLIENT_ID = ${GOOGLE_SERVER_CLIENT_ID}
GOOGLE_REVERSED_CLIENT_ID = ${GOOGLE_REVERSED_CLIENT_ID}
EOF
