// Bu dosya `docs/olustur.py` tarafından üretiliyor. Elle düzenleme —
// kaynak metinler docs/gizlilik.md, docs/kosullar.md, docs/en/privacy.md, docs/en/terms.md.

enum LegalBlock {
    case baslik(String)
    case altbaslik(String)
    case paragraf(String)
    case madde(String)
}

enum LegalTexts {
    static let gizlilik: [LegalBlock] = [
        .baslik("Gizlilik Politikası"),
        .paragraf("Son güncelleme: 11 Eylül 2026"),
        .paragraf("Common, üniversite kampüsü topluluklarına yönelik; kampüs paylaşımları, kulüpler, buluşmalar ve mesajlaşma sunan bir sosyal uygulamadır. Bu metin, uygulamanın hangi bilgileri topladığını, neden topladığını ve bu bilgilerle ne yaptığını anlatır. Sade tutmaya çalıştık."),
        .altbaslik("Topladığımız bilgiler"),
        .paragraf("Hesabını açarken: e-posta adresin (Google veya Apple ile giriş yaptığında bize iletilen adres), adın, doğum tarihin, üniversiten, bölümün ve sınıfın. Doğum tarihini yaşını hesaplamak ve 18 yaş sınırını uygulamak için istiyoruz."),
        .paragraf("Profilini doldururken: kendini anlattığın metin, ilgi alanların ve profil fotoğrafların."),
        .paragraf("Uygulamayı kullanırken: paylaştığın gönderiler ve story'ler, yazdığın yorumlar ve mesajlar, beğendiğin ve kaydettiğin gönderiler, katıldığın kulüpler, \"şu an buradayım\" diye seçtiğin kampüs noktası, kimlerle bağlantı kurduğun ve son aktif olduğun zaman."),
        .paragraf("Otomatik olarak: oturumunu açık tutmak için gereken teknik kayıtlar."),
        .paragraf("Konumunu telefondan okumuyoruz. Kampüste nerede olduğun yalnızca senin listeden elle seçtiğin yerdir ve seçtiğin süre dolunca kendiliğinden kalkar."),
        .altbaslik("Bu bilgileri ne için kullanıyoruz"),
        .paragraf("Hesabını açmak ve girişini sürdürmek; profilini ve paylaşımlarını diğer öğrencilere göstermek; kampüs içeriği üzerinden insanlarla bağlantı kurmanı ve kabul edilen mesaj isteklerinden sonra konuşmanı sağlamak; şikayet edilen içerikleri incelemek ve kuralları uygulamak."),
        .paragraf("Reklam göstermiyoruz. Bilgilerini reklam amacıyla kimseye satmıyor, kiralamıyor veya devretmiyoruz."),
        .altbaslik("Kimler neyi görebiliyor"),
        .madde("Profilin, gönderilerin ve story'lerin: uygulamayı kullanan diğer öğrenciler görebilir. Engellediğin veya seni engelleyen kişiler bunun dışındadır."),
        .madde("Mesajların: uygulama içinde konuşmanın taraflarına gösterilir. Bir mesaj şikayet edildiğinde, o mesajın içeriği ve şikayet gerekçesi yetkili moderatörlere iletilir; bu işlem tüm konuşmayı moderatörlere açmaz."),
        .madde("Seçtiğin kampüs noktası: yalnızca sen görünür olmayı seçtiğin sürece ve yalnızca uygulamadaki diğer öğrenciler görebilir."),
        .madde("Bir story'yi izlemen: o story'nin sahibi seni izleyenler listesinde görür ve kaç kez izlediğin de ona görünür. Story kaybolduğunda bu bilgi de silinir."),
        .madde("E-posta adresin ve doğum tarihin: diğer kullanıcılara gösterilmez."),
        .madde("Engellediğin kişiler: engellediğin kişi bunu göremez."),
        .altbaslik("Bilgilerin nerede tutuluyor"),
        .paragraf("Veriler, altyapı sağlayıcımız Supabase'in sunucularında saklanır. Bağlantılar şifreli (HTTPS) kurulur. Mesajlar sunucuda saklanır; uygulama uçtan uca şifreli mesajlaşma sunduğunu iddia etmez. Profil fotoğrafları ve diğer medya özel depolama alanlarında tutulur; uygulama bunlara erişim kurallarına tabi, süreli bağlantılarla ulaşır. Geçerli bir bağlantıyı alan kişi, süresi dolana kadar medyayı uygulama dışında da açabilir."),
        .paragraf("Giriş için Google ve Apple'ın kimlik doğrulama servislerini kullanıyoruz. Bu servisler kendi gizlilik politikalarına tabidir ve bize yalnızca kimliğini doğrulayan asgari bilgiyi iletirler; şifreni hiçbir zaman görmeyiz."),
        .altbaslik("Abonelik ve ödeme"),
        .paragraf("Ödemeyi App Store üzerinden Apple işler. Tam kart numaranı veya kart güvenlik kodunu istemeyiz, görmeyiz ve saklamayız."),
        .paragraf("Abonelikle ilgili işlediğimiz bilgiler, hesabına bağlı olarak şunlardır: hangi kademede olduğun (ücretsiz, Plus, Pro), aboneliğinin bitiş tarihi ve Apple'ın o aboneliğe verdiği işlem kimlikleri."),
        .paragraf("Abonelikleri doğrulamak ve satın alımları geri yüklemek için RevenueCat hizmetini kullanırız. Uygulama içi kullanıcı kimliğin, satın alınan ürün, satın alma ve yenileme/sona erme bilgileri ile Apple işlem kayıtları bu hizmet tarafından işlenir. Uygulama kodu RevenueCat'e mesajlarını, fotoğraflarını veya elle seçtiğin kampüs noktasını göndermez."),
        .paragraf("Bunları özellik sınırlarını uygulayabilmek için saklıyoruz. Kademeni yalnızca sen görebilirsin — başka kullanıcılar kimin abone olduğunu göremez."),
        .altbaslik("Ne kadar süre tutuyoruz"),
        .paragraf("Hesabın açık olduğu sürece. Story'ler 10 saat sonra kendiliğinden kaybolur."),
        .paragraf("Hesabını uygulama içinden Profil → Hesabı kalıcı olarak sil yolundan silebilirsin. Sildiğinde profilin, gönderilerin, story'lerin, mesajların, fotoğrafların ve bağlantıların sunuculardan kaldırılır. Bu işlem geri alınamaz."),
        .paragraf("Hesabını silmek App Store aboneliğini otomatik iptal etmez. Aboneliğini Apple hesap ayarlarından ayrıca yönetmelisin. Apple ve RevenueCat'in ödeme/işlem kayıtlarına ilişkin saklama süreçleri kendi hizmet koşullarına tabidir."),
        .altbaslik("Yaş sınırı"),
        .paragraf("Common 18 yaşından küçüklerin kullanımına kapalıdır. 18 yaşından küçük olduğunu öğrendiğimiz hesapları kapatırız."),
        .altbaslik("Hakların"),
        .paragraf("6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında; hangi verilerinin işlendiğini öğrenme, düzeltilmesini veya silinmesini isteme ve işlenmesine itiraz etme hakkına sahipsin. Profil bilgilerini uygulama içinden dilediğin zaman değiştirebilir, hesabını dilediğin zaman silebilirsin. Diğer talepler için aşağıdaki adresten bize yazabilirsin."),
        .altbaslik("Değişiklikler"),
        .paragraf("Bu metni güncellersek en üstteki tarihi değiştirir, önemli bir değişiklik olursa uygulama içinde bildiririz."),
        .altbaslik("İletişim"),
        .paragraf("E-posta: 220207018@yalova.edu.tr"),
        .paragraf("Şikayetlere ve veri taleplerine 24 saat içinde dönüyoruz."),
    ]

    static let kosullar: [LegalBlock] = [
        .baslik("Kullanım Koşulları"),
        .paragraf("Son güncelleme: 11 Eylül 2026"),
        .paragraf("Common'u kullanarak bu koşulları kabul etmiş olursun. Kabul etmiyorsan uygulamayı kullanma."),
        .altbaslik("Kimler kullanabilir"),
        .paragraf("Common, üniversite öğrencilerine yöneliktir ve 18 yaşını doldurmuş olman gerekir. Hesabını kendi adına açarsın; başkasının kimliğine bürünemez, sahte profil oluşturamazsın. Hesabını başkasına devredemez, paylaşamazsın."),
        .paragraf("Google veya Apple ile giriş yapabilirsin. Giriş için .edu.tr adresi şartı aranmaz; giriş yapmış olmak üniversite öğrencisi olduğunun doğrulandığı anlamına gelmez."),
        .altbaslik("Paylaştığın içerikten sen sorumlusun"),
        .paragraf("Uygulamaya yüklediğin fotoğraf, yazı ve mesajların sorumluluğu sana aittir. Yalnızca paylaşma hakkına sahip olduğun içerikleri paylaş."),
        .paragraf("Paylaştığın içerik sana ait kalır. Bize yalnızca bu içeriği uygulama içinde diğer kullanıcılara gösterebilmemiz için gereken izni vermiş olursun; bu izin içeriğini sildiğinde sona erer."),
        .altbaslik("Kabul edilmeyen davranışlar"),
        .paragraf("Aşağıdakilere sıfır tolerans uygulanır:"),
        .madde("Taciz, tehdit, hakaret, ısrarlı rahatsız etme"),
        .madde("Nefret söylemi; ırk, etnik köken, din, cinsiyet, cinsel yönelim, engellilik veya benzeri özellikler üzerinden hedef gösterme"),
        .madde("Cinsel içerik, çıplaklık, müstehcen paylaşım"),
        .madde("Şiddet içeren, kendine zarar vermeyi özendiren veya yasa dışı içerik"),
        .madde("Başkasının fotoğrafını, kimliğini veya özel bilgilerini izinsiz paylaşmak"),
        .madde("Sahte hesap, spam, dolandırıcılık, ticari tanıtım"),
        .madde("18 yaşından küçüklere yönelik her türlü içerik veya yaklaşım"),
        .altbaslik("Şikayet, engelleme ve moderasyon"),
        .paragraf("Profilleri, gönderileri, yorumları, story'leri ve aldığın mesajları uygulama içinden şikayet edebilirsin. Bir içeriği şikayet ettiğinde ilgili içerik ve gerekçen moderatörlere iletilir. Profiller ve sohbetler üzerinden kişileri engelleyebilirsin; engellediğin kişi seninle iletişim kuramaz."),
        .paragraf("Belirli açık hakaret ve müstehcen ifadeler paylaşılmadan önce metin kontrolünden geçirilir. Bu kontrol her ihlali tespit edemez; fotoğraf ve videoların otomatik olarak tamamen denetlendiği anlamına gelmez. Kontrolden kaçan veya başka şekilde kuralları ihlal eden içerikleri şikayet edebilirsin."),
        .paragraf("Bize ulaşan şikayetleri 24 saat içinde inceler; kuralları ihlal eden içeriği kaldırır ve gerekirse hesabı kalıcı olarak kapatırız. Ciddi durumlarda hesabı incelemeyi beklemeden askıya alabiliriz. Bu kararlar için ayrıca bildirimde bulunmak zorunda değiliz."),
        .altbaslik("Hesabının kapatılması"),
        .paragraf("Kuralları ihlal ettiğini tespit edersek hesabını uyarı yapmadan kapatabiliriz. Sen de hesabını dilediğin zaman uygulama içinden Profil → Hesabı kalıcı olarak sil yolundan silebilirsin."),
        .paragraf("Hesap silmek App Store aboneliğini otomatik iptal etmez. Aboneliğini Apple hesap ayarlarından ayrıca yönetmelisin. Apple ile giriş izni otomatik kaldırılamadığında uygulama, bu izni Apple hesabından kaldırman için yönergeleri gösterir."),
        .altbaslik("Abonelikler"),
        .paragraf("Common'un temel özellikleri ücretsizdir. Common Plus ve Common Pro, isteğe bağlı haftalık aboneliklerdir; abone olmadan da uygulamayı kullanmaya devam edebilirsin."),
        .paragraf("Satın alma App Store üzerinden yapılır ve ücret App Store hesabına yansır. Abonelik, dönemin bitiminden en az 24 saat önce iptal edilmezse kendiliğinden yenilenir ve aynı tutar tekrar tahsil edilir."),
        .paragraf("İptal, App Store hesap ayarlarından yapılır — uygulama içinden iptal edemeyiz. İptal ettiğinde mevcut dönemin sonuna kadar aboneliğin devam eder. Ücret iadesi talepleri de Apple'a iletilir; ödemeyi biz almadığımız için iade işlemini biz yapamıyoruz."),
        .paragraf("Fiyatlar değişebilir. Devam eden bir aboneliğin fiyatı değişirse Apple seni bilgilendirir ve onayını ister. Abonelik hesabına bağlıdır, başkasına devredilemez. Hangi özelliklerin ücretli olduğunu zamanla değiştirebiliriz; ödemesini yaptığın dönem boyunca sana tanıdığımız özellikleri geri almayız."),
        .altbaslik("Sorumluluk sınırı"),
        .paragraf("Common kampüs içi iletişimi ve buluşmaları kolaylaştıran bir sosyal araçtır; kullanıcıların kimliğini, söylediklerinin doğruluğunu veya niyetlerini garanti etmez. Uygulamadan tanıdığın kişilerle buluşurken kendi güvenliğinden sen sorumlusun: ilk buluşmaları kalabalık ve açık yerlerde yapmanı, yakınlarından birine haber vermeni öneririz."),
        .paragraf("Uygulama \"olduğu gibi\" sunulur. Kesintisiz veya hatasız çalışacağını taahhüt etmiyoruz. Yasaların izin verdiği ölçüde, uygulamanın kullanımından doğan dolaylı zararlardan sorumlu değiliz."),
        .altbaslik("Değişiklikler"),
        .paragraf("Bu koşulları güncelleyebiliriz. Önemli bir değişiklikte uygulama içinde bildiririz; değişiklikten sonra kullanmaya devam etmen yeni koşulları kabul ettiğin anlamına gelir."),
        .altbaslik("Uygulanacak hukuk"),
        .paragraf("Bu koşullara Türkiye Cumhuriyeti hukuku uygulanır."),
        .altbaslik("İletişim"),
        .paragraf("E-posta: 220207018@yalova.edu.tr"),
        .paragraf("Şikayetlere ve veri taleplerine 24 saat içinde dönüyoruz."),
    ]

    static let privacy: [LegalBlock] = [
        .baslik("Privacy Policy"),
        .paragraf("Last updated: 11 September 2026"),
        .paragraf("Common is a social app for university campus communities, with campus posts, clubs, meetups and messaging. This document explains what information the app collects, why it collects it, and what we do with it. English translation of the Turkish original; the Turkish version governs."),
        .altbaslik("Information we collect"),
        .paragraf("When you create an account: your email address (provided to us when you sign in with Google or Apple), your name, date of birth, university, department and year of study. We ask for your date of birth to calculate your age and to enforce the minimum age of 18."),
        .paragraf("When you fill in your profile: your bio, interests and profile photos."),
        .paragraf("As you use the app: the posts and stories you share, the comments and messages you write, the posts you like and save, the clubs you join, the campus location you choose to appear at, who you connect with, and when you were last active."),
        .paragraf("Automatically: the technical records needed to keep you signed in."),
        .paragraf("We do not read your location from your device. Where you appear on campus is only the place you pick yourself from a list, and it clears automatically when the time you chose runs out."),
        .altbaslik("How we use this information"),
        .paragraf("To create your account and keep you signed in; to show your profile and posts to other students; to help you connect through campus content and talk after a message request is accepted; and to review reported content and enforce our rules."),
        .paragraf("We do not show ads. We do not sell, rent or transfer your information to anyone for advertising."),
        .altbaslik("Who can see what"),
        .madde("Your profile, posts and stories: other students using the app. People you block, or who block you, are excluded."),
        .madde("Your messages: shown to the participants of the conversation in the app. When a message is reported, that message's content and the report reason are shared with authorized moderators; this does not give moderators access to the entire conversation."),
        .madde("The campus place you pick: only while you choose to be visible, and only to other students in the app."),
        .madde("Watching someone's story: the owner of that story sees you in their list of viewers, including how many times you watched it. This is deleted with the story."),
        .madde("Your email address and date of birth: never shown to other users."),
        .madde("People you block: cannot see that you blocked them."),
        .altbaslik("Where your data is stored"),
        .paragraf("Data is stored on the servers of our infrastructure provider, Supabase. Connections are encrypted (HTTPS). Messages are stored on the server; we do not claim to provide end-to-end encrypted messaging. Profile photos and other media are held in private storage; the app accesses them through access rules and time-limited links. Someone who receives a valid link can open that media outside the app until the link expires."),
        .paragraf("We use Google's and Apple's authentication services for sign-in. They are governed by their own privacy policies and pass us only the minimum information needed to verify your identity; we never see your password."),
        .altbaslik("Subscriptions and payment"),
        .paragraf("Apple processes payments through the App Store. We do not request, see or store your full card number or card security code."),
        .paragraf("Subscription information we process, tied to your account, includes: which plan you are on (free, Plus, Pro), when your subscription expires, and the identifier Apple assigns to the transactions."),
        .paragraf("We use RevenueCat to validate subscriptions and restore purchases. This service processes your app user identifier, purchased product, purchase and renewal/expiration information, and Apple transaction records. Our app code does not send your messages, photos or manually selected campus place to RevenueCat."),
        .paragraf("We store this in order to enforce feature limits. Only you can see your own plan — other users cannot tell who is subscribed."),
        .altbaslik("How long we keep it"),
        .paragraf("For as long as your account exists. Stories disappear automatically after 10 hours."),
        .paragraf("You can delete your account from inside the app: Profile → Delete account permanently. Doing so removes your profile, posts, stories, messages, photos and connections from our servers. This cannot be undone."),
        .paragraf("Deleting your account does not automatically cancel an App Store subscription. You must manage your subscription separately in your Apple account settings. Apple and RevenueCat retain payment/transaction records under their respective service terms."),
        .altbaslik("Age limit"),
        .paragraf("Common is not available to anyone under 18. We close accounts we learn belong to someone under 18."),
        .altbaslik("Your rights"),
        .paragraf("Under Turkish Personal Data Protection Law No. 6698 (KVKK) you have the right to learn which of your data is processed, to ask for it to be corrected or deleted, and to object to its processing. You can change your profile at any time from inside the app and delete your account at any time. For anything else, write to us at the address below."),
        .altbaslik("Changes"),
        .paragraf("If we update this document we will change the date at the top, and we will notify you in the app if the change is significant."),
        .altbaslik("Contact"),
        .paragraf("Email: 220207018@yalova.edu.tr"),
        .paragraf("We respond to reports and data requests within 24 hours."),
    ]

    static let terms: [LegalBlock] = [
        .baslik("Terms of Use"),
        .paragraf("Last updated: 11 September 2026"),
        .paragraf("By using Common you accept these terms. If you do not accept them, do not use the app. English translation of the Turkish original; the Turkish version governs."),
        .altbaslik("Who can use it"),
        .paragraf("Common is intended for university students and you must be 18 or older. You open an account in your own name; you may not impersonate anyone or create a fake profile. You may not transfer or share your account."),
        .paragraf("You can sign in with Google or Apple. A .edu.tr address is not required; signing in does not verify that you are a university student."),
        .altbaslik("You are responsible for what you share"),
        .paragraf("You are responsible for the photos, text and messages you upload. Only share content you have the right to share."),
        .paragraf("Content you share remains yours. You grant us only the permission needed to display it to other users inside the app, and that permission ends when you delete the content."),
        .altbaslik("Unacceptable behaviour"),
        .paragraf("We operate a zero tolerance policy for the following:"),
        .madde("Harassment, threats, insults, persistent unwanted contact"),
        .madde("Hate speech; targeting people over race, ethnicity, religion, gender, sexual orientation, disability or similar characteristics"),
        .madde("Sexual content, nudity, obscene material"),
        .madde("Violent content, content encouraging self-harm, or anything unlawful"),
        .madde("Sharing someone else's photo, identity or private information without consent"),
        .madde("Fake accounts, spam, fraud, commercial promotion"),
        .madde("Any content directed at, or approach towards, people under 18"),
        .altbaslik("Reporting, blocking and moderation"),
        .paragraf("You can report profiles, posts, comments, stories and messages you receive inside the app. Reporting content shares that content and your reason with moderators. You can block people from their profiles or conversations; someone you block cannot contact you."),
        .paragraf("Text is checked for certain explicit insults and obscene phrases before publication. This check cannot detect every violation and does not mean that photos and videos are fully moderated automatically. Please report content that gets through the check or otherwise breaks our rules."),
        .paragraf("We review reports within 24 hours, remove content that breaks the rules and, where necessary, permanently close the account. In serious cases we may suspend an account before completing our review. We are not obliged to give separate notice of these decisions."),
        .altbaslik("Closing your account"),
        .paragraf("If we find that you have broken these rules we may close your account without warning. You can delete your own account at any time from inside the app: Profile → Delete account permanently."),
        .paragraf("Deleting your account does not automatically cancel an App Store subscription. Manage your subscription separately in your Apple account settings. If Sign in with Apple permission cannot be revoked automatically, the app shows instructions for removing that permission from your Apple account."),
        .altbaslik("Subscriptions"),
        .paragraf("Common's core features are free. Common Plus and Common Pro are optional weekly subscriptions; you can keep using the app without subscribing."),
        .paragraf("Purchases are made through the App Store and charged to your App Store account. A subscription renews automatically and is charged again unless you cancel at least 24 hours before the end of the current period."),
        .paragraf("Cancellation is done in your App Store account settings — we cannot cancel a subscription for you. When you cancel, your subscription runs until the end of the current period. Refund requests also go to Apple; because we never receive the payment, we cannot issue refunds ourselves."),
        .paragraf("Prices may change. If the price of an active subscription changes, Apple will notify you and ask for your consent. A subscription is tied to your account and cannot be transferred. We may change which features require a paid plan; we will not take away features you have already paid for during that period."),
        .altbaslik("Limits of our responsibility"),
        .paragraf("Common is a social tool for campus communication and meetups; it does not guarantee the identity, honesty or intentions of its users. You are responsible for your own safety when meeting someone you know through the app: we recommend meeting first in busy public places and telling someone close to you where you are going."),
        .paragraf("The app is provided \"as is\". We do not promise it will run without interruption or error. To the extent permitted by law, we are not liable for indirect damages arising from use of the app."),
        .altbaslik("Changes"),
        .paragraf("We may update these terms. We will notify you in the app if a change is significant; continuing to use the app after a change means you accept the new terms."),
        .altbaslik("Governing law"),
        .paragraf("These terms are governed by the laws of the Republic of Türkiye."),
        .altbaslik("Contact"),
        .paragraf("Email: 220207018@yalova.edu.tr"),
    ]

}
